### ISSUE TITLE
SameSite cookie issue

### ISSUE THREAD

**Issue by onlinebizsoft** [forter/forter-magento2#104]
We got these in our browser console when we browse our website with forter script installed 

Cookie “forterToken” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Cookie “forterToken” has been rejected for invalid domain.

**Comment by cristianbalajosf** [comment]
fixed was made for this, it will be included in the next release ( v 2.4.12 ).
