### ISSUE TITLE
SyntaxError: Unexpected token '>'

### ISSUE THREAD

**Issue by onlinebizsoft** [forter/forter-magento2#107]
For any browser/visitors who don't have ES6 support then they would get this error

We have traced our logs and we found this happening with some certain user agent like Daum 4.1, PhantomJS

Reference https://stackoverflow.com/questions/44203852/grunt-karma-phantomjs-syntaxerror-unexpected-token
It doesn't create a problem but it should be avoided

**Comment by cristianbalajosf** [comment]
Couldn't replicate this.
This should be handled on Forter end as the js is loaded from them.

**Comment by onlinebizsoft** [comment]
@cristianbalajosf sorry I thought this is official github of Forter?

**Comment by cristianbalajosf** [comment]
Hi, the OSF team is handling the magento side of Forter .
