### ISSUE TITLE
getProductCategories always returns null if there is any catagory ids found

### ISSUE THREAD

**Issue by nishanthan1989** [forter/forter-magento2#118]
https://github.com/forter/forter-magento2/blob/a7ee344c2726525504c85b9db9c12549252f2cc1/Model/RequestBuilder/Cart.php#L146

should be corrected to 

`if (!$categoryIds) {
            return null;
        }`

**Comment by cristianbalajosf** [comment]
Hi @rachel-yankelevitz ,
This will be fixed and will be included in the next release.
