### ISSUE TITLE
Using wrong config path for declined email enabled configuration 

### ISSUE THREAD

**Issue by nishanthan1989** [forter/forter-magento2#119]
https://github.com/forter/forter-magento2/blob/a7ee344c2726525504c85b9db9c12549252f2cc1/Model/Sendmail.php#L15

the correct one should be _sendmail_on_decline/sendmail_on_decline_enabled_

as used in here 

https://github.com/forter/forter-magento2/blob/a7ee344c2726525504c85b9db9c12549252f2cc1/Model/Config.php#L226C46-L226C93

**Comment by cristianbalajosf** [comment]
Hi @rachel-yankelevitz ,
This will be fixed and will be included in the next release.
