### ISSUE TITLE
Issue when change password in my account

### ISSUE THREAD

**Issue by kevinonlinebiz** [forter/forter-magento2#38]
Hello !
I use magento 2 version 2.4.1.
I have problem when change password in my account .
http://i.imgur.com/cJDgo7J.png
I checked and this error is caused wrong code in plugin module forter.
Path File: vendor/forter/magento2-module-forter/Plugin/Customer/Model/AccountManagement.php.
http://i.imgur.com/PiTf9kZ.png
Pls fix it.

I updated to avoid this error.You can refer to it.
http://i.imgur.com/X5mEL7Y.png
Pls confirm email kevin@onlinebizsoft.com if module updated lastest.
Thanks!

**Comment by cristianbalajosf** [comment]
couldn't replicate this , this is no longer an issue.
