### ISSUE TITLE
Error when placing an order in Magento backend

### ISSUE THREAD

**Issue by jayd59** [forter/forter-magento2#48]
Hello,

When we placed an order in the backend, we have an error "undefined variable". See below. 

<img width="1288" alt="Capture d’écran 2021-03-19 à 13 55 44" src="https://user-images.githubusercontent.com/21152664/111787558-5f10ce00-88bf-11eb-895e-b6c1f1a18132.png">

I added a simple product, with an existing customer, billing address = shipping address, and offline payment method and freeshipping as shipping method.

Module Version = 2.0.24

Jeremy

**Comment by cristianbalajosf** [comment]
couldn't replicate this , this is no longer an issue.
