### ISSUE TITLE
Placing orders with Gift Cards not working

### ISSUE THREAD

**Issue by dverkade** [forter/forter-magento2#59]
**What is the issue**

Forter decision throws the error: "Additional properties not allowed: beneficiaries"

![image](https://user-images.githubusercontent.com/1058480/117510517-806f6b80-af8c-11eb-87d2-65a659b52154.png)

**What is the cause**

On this line it add the beneficiary: https://github.com/forter/forter-magento2/blob/master/Model/RequestBuilder/Cart.php#L104

However a beneficiary can't be added according to the API documentation to a cart item: 
https://portal.forter.com/app/developer/api/api/data-objects/Item

**Comment by cristianbalajosf** [comment]
couldn't replicate this , this is no longer an issue.
