### ISSUE TITLE
AbstractApi has an undefined property forterErrorLogger

### ISSUE THREAD

**Issue by dverkade** [forter/forter-magento2#60]
**Error thrown:** 

Undefined property: Forter\Forter\Model\AbstractApi::$forterErrorLogger in /var/www/magento/vendor/forter/magento2-module-forter/Model/AbstractApi.php

**Cause:** 

forterErrorLogger is not defined, see following class and line item: 

https://github.com/forter/forter-magento2/blob/79632b4769316ee436bc1234cc8a5b45d2e60572/Model/AbstractApi.php#L176

**Comment by onlinebizsoft** [comment]
@dondrich @pniel-cohen @orenyomtov any comment on this?

**Comment by dondrich** [comment]
@onlinebizsoft Thanks for raising this issue!

This has been fixed. Please update to our latest release if you're still facing this problem.
